PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(57,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(58,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(59,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(60,'2026_05_22_115951_create_flats_table',1);
INSERT INTO migrations VALUES(61,'2026_05_22_121744_create_meter_readings_table',1);
INSERT INTO migrations VALUES(62,'2026_05_24_000247_create_bills_table',1);
INSERT INTO migrations VALUES(63,'2026_05_24_000341_create_bill_details_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "phone" varchar not null, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Ashique','01785636359','$2y$12$KQFLROMBXqTJPbLb2eHseePEXsglxxkwVjcXTmoprYzTpEhYYnHru',NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('UCtCxBwTML7LPlplsQVzfeRMRSCE9hOg6EHbdP23',1,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36','eyJfdG9rZW4iOiJQakRDZVNnWnV6cWlEU01xZHVwc3UyODFuMHBGTXZvUzByVldIV25WIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwXC9tZXRlci1yZWFkaW5ncyIsInJvdXRlIjoibWV0ZXItcmVhZGluZ3MuaW5kZXgifSwiX2ZsYXNoIjp7Im9sZCI6W10sIm5ldyI6W119LCJsb2dpbl93ZWJfNTliYTM2YWRkYzJiMmY5NDAxNTgwZjAxNGM3ZjU4ZWE0ZTMwOTg5ZCI6MX0=',1780520322);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" varchar not null, "queue" varchar not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "flats" ("id" integer primary key autoincrement not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO flats VALUES(1,'2A',NULL,NULL);
INSERT INTO flats VALUES(2,'2B',NULL,NULL);
INSERT INTO flats VALUES(3,'3A',NULL,NULL);
INSERT INTO flats VALUES(4,'3B',NULL,NULL);
INSERT INTO flats VALUES(5,'4A',NULL,NULL);
INSERT INTO flats VALUES(6,'4B',NULL,NULL);
INSERT INTO flats VALUES(7,'5A',NULL,NULL);
INSERT INTO flats VALUES(8,'5B',NULL,NULL);
INSERT INTO flats VALUES(9,'6A',NULL,NULL);
INSERT INTO flats VALUES(10,'6B',NULL,NULL);
INSERT INTO flats VALUES(11,'7A',NULL,NULL);
INSERT INTO flats VALUES(12,'7B',NULL,NULL);
INSERT INTO flats VALUES(13,'8A',NULL,NULL);
INSERT INTO flats VALUES(14,'8B',NULL,NULL);
INSERT INTO flats VALUES(15,'9A',NULL,NULL);
INSERT INTO flats VALUES(16,'9B',NULL,NULL);
INSERT INTO flats VALUES(17,'10A',NULL,NULL);
INSERT INTO flats VALUES(18,'10B',NULL,NULL);
CREATE TABLE IF NOT EXISTS "meter_readings" ("id" integer primary key autoincrement not null, "flat_id" integer not null, "reading_date" date not null, "reading_unit" numeric not null, "created_at" datetime, "updated_at" datetime, foreign key("flat_id") references "flats"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "bills" ("id" integer primary key autoincrement not null, "name" varchar not null, "bill_for_month" date, "price_per_kg" numeric not null, "price_per_m3" numeric not null, "total_used_m3" numeric not null default '0', "total_used_kg" numeric not null default '0', "total_bill" numeric not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "bill_details" ("id" integer primary key autoincrement not null, "bill_id" integer not null, "flat_id" integer not null, "previous_reading" numeric not null, "current_reading" numeric not null, "used_m3" numeric not null, "used_kg" numeric not null, "bill_for_month" date not null, "created_at" datetime, "updated_at" datetime, foreign key("bill_id") references "bills"("id") on delete cascade, foreign key("flat_id") references "flats"("id") on delete cascade);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',63);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('flats',18);
CREATE UNIQUE INDEX "users_phone_unique" on "users" ("phone");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE INDEX "failed_jobs_connection_queue_failed_at_index" on "failed_jobs" ("connection", "queue", "failed_at");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
COMMIT;
